spring:
  profiles:
    active: prod
build:
  version: "5.0"

accounts:
  message: "Welcome to EazyBank accounts related Dummy 10 APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
